# Generated by Django 4.2.16 on 2024-11-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='trailerlink',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='running_time',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
        migrations.AddField(
            model_name='review',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.user'),
        ),
    ]
