# Generated by Django 4.2.16 on 2024-11-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rating_review_remove_booking_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.user'),
            preserve_default=False,
        ),
    ]
