# Generated by Django 4.2.16 on 2024-11-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='ADMIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.admin'),
            preserve_default=False,
        ),
    ]
