# Generated by Django 4.2.16 on 2024-12-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_admin_password_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ADMIN',
        ),
    ]
