# Generated by Django 4.2.16 on 2024-12-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_movie_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ADMIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.admin'),
            preserve_default=False,
        ),
    ]
