# Generated by Django 4.2.16 on 2024-12-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ADMIN',
        ),
    ]
