# Generated by Django 4.2.16 on 2024-12-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_remove_movie_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviecategoryname', models.CharField(max_length=100)),
                ('ADMIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.admin')),
            ],
        ),
    ]
