# Generated by Django 4.2.16 on 2024-12-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
